/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (pings the database, 1 s timeout) */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Email is trimmed, lower-cased and normalised to NFC; a duplicate (case-insensitive, and NFC/NFD spellings are the same address) is `409 email_taken`. Password: 10-128 characters and not equal to the email. Display name: 1-100 characters after trimming, no control or format characters (see the field). Rate limit: 5 per hour per IP (counted once the input is valid). A cookie-less request needs no Origin; one that carries a session cookie must satisfy the CSRF origin check.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description A wrong password and an unknown email give the identical `401 invalid_credentials` (same body, same work). Every login issues a new session token; a session cookie sent with the request is revoked. Failures are limited to 10 per 15 minutes per IP+email and 100 per 15 minutes per IP.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out (idempotent)
         * @description Deletes the session and clears the cookie. Always 204, also when nobody is signed in.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an email address with the token from the verification email
         * @description Tokens are 32 random bytes (base64url), stored only as SHA-256, valid 24 hours and single use. An unknown, expired, used or wrong-purpose token (a reset token, for example) is `400 invalid_token`. Registration and `verify-email/resend` send the email; the link is `SMEM_PUBLIC_BASE_URL/verify-email?token=...`.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a new verification email to the signed-in user
         * @description At most 3 per hour per user (`429 rate_limited` with `Retry-After`). Earlier links stay valid until they expire. Takes no body.
         */
        post: operations["resendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a password reset email
         * @description Always `202 {}` for a well-formed address, whether or not an account exists; the email (valid link for 1 hour, in the user's `locale`) goes out in the background and only when the account exists, so neither the body nor the timing tells them apart. Limits: 5 per hour per IP and 3 per hour per address (counted for unknown addresses too). The address is trimmed, lower-cased and NFC-normalised like at login; one that is not an email at all is `400 invalid_email`.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with the token from the reset email
         * @description The token is valid 1 hour and single use; an unknown, expired, used or wrong-purpose token is `400 invalid_token`. The password follows the registration rules (NFKC, 10-128 characters, not the email); a rejected password is `400 weak_password` and does not use up the token. On success every session of the user is deleted (sign in again), and the user's other open reset links stop working.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description Sliding expiry: once more than half of the 30-day lifetime has elapsed the expiry is extended and the cookie is sent again.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/yearbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's yearbooks
         * @description Only the caller's books, newest `updated_at` first (editing the book or its profile updates it). Pass `next_cursor` back as `cursor` for the next page; `next_cursor` is null on the last page. A malformed or tampered cursor is `400 invalid_cursor`.
         */
        get: operations["listYearbooks"];
        put?: never;
        /**
         * Create a yearbook (and its owner profile)
         * @description Creates the book and one owner profile whose `full_name` is the user's display name. A user owns at most 20 books (`409 limit_reached`). Unknown fields (for example `owner_id`) are rejected with `400 unknown_field`. Text fields are normalised to NFC and trimmed; control characters (Cc), format characters (Cf, except U+200D) and line/paragraph separators are rejected with `invalid_<field>`.
         */
        post: operations["createYearbook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/yearbooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Read one yearbook with its profile
         * @description A missing book and a book owned by someone else both answer `404 not_found`.
         */
        get: operations["getYearbook"];
        put?: never;
        post?: never;
        /**
         * Delete a yearbook
         * @description Hard-deletes the book and its profile.
         */
        delete: operations["deleteYearbook"];
        options?: never;
        head?: never;
        /**
         * Partially update a yearbook
         * @description Only the fields present change. An empty string clears an optional text field; `graduation_year: null` clears the year. A JSON null on any other field counts as absent. Unknown fields are `400 unknown_field`.
         */
        patch: operations["updateYearbook"];
        trace?: never;
    };
    "/v1/yearbooks/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the owner's profile information
         * @description Replaces every field: an omitted optional field is cleared. Unknown fields (for example `is_owner`) are `400 unknown_field`. Birthday is personal data and is never logged.
         */
        put: operations["replaceYearbookProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * @description Opaque ULID.
             * @example 01J9Z3K6V8Q4M7N2P5R8T0W1XY
             */
            id: string;
            email: string;
            email_verified: boolean;
            display_name: string;
            /** @enum {string} */
            locale: "en" | "vi";
            /** Format: date-time */
            created_at: string;
        };
        UserEnvelope: {
            user: components["schemas"]["User"];
        };
        Profile: {
            /** @description Opaque ULID. */
            id: string;
            is_owner: boolean;
            full_name: string;
            /** @description Empty when not set. */
            nickname: string;
            /** Format: date */
            birthday: string | null;
            quote: string;
            hobbies: string;
            future_plans: string;
        };
        Yearbook: {
            /**
             * @description Opaque ULID.
             * @example 01J9Z3K6V8Q4M7N2P5R8T0W1XY
             */
            id: string;
            title: string;
            /** @description Empty when not set. */
            school_name: string;
            /** @description Empty when not set. */
            class_name: string;
            graduation_year: number | null;
            motto: string;
            /** @enum {string} */
            language: "en" | "vi";
            /** @enum {string} */
            page_size: "A5" | "A4";
            /** @description Null until a template is chosen. */
            template_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            profile: components["schemas"]["Profile"];
        };
        YearbookEnvelope: {
            yearbook: components["schemas"]["Yearbook"];
        };
        YearbookCreate: {
            title: string;
            school_name?: string;
            class_name?: string;
            graduation_year?: number | null;
            motto?: string;
            /** @enum {string} */
            language: "en" | "vi";
            /**
             * @default A5
             * @enum {string}
             */
            page_size: "A5" | "A4";
        };
        YearbookPatch: {
            title?: string;
            school_name?: string;
            class_name?: string;
            graduation_year?: number | null;
            motto?: string;
            /** @enum {string} */
            language?: "en" | "vi";
            /** @enum {string} */
            page_size?: "A5" | "A4";
        };
        ProfileInput: {
            full_name: string;
            nickname?: string;
            /**
             * Format: date
             * @description YYYY-MM-DD, a real date strictly before today (UTC) and not before 1900-01-01.
             */
            birthday?: string | null;
            quote?: string;
            hobbies?: string;
            future_plans?: string;
        };
        /** @description Shared error envelope. `code` is a stable snake_case contract (clients localise it); `message` is English text meant for logs. */
        Error: {
            error: {
                /**
                 * @example not_found
                 * @example method_not_allowed
                 * @example payload_too_large
                 * @example internal_error
                 * @example not_ready
                 * @example invalid_credentials
                 * @example unauthenticated
                 * @example rate_limited
                 * @example invalid_token
                 * @example limit_reached
                 * @example unknown_field
                 */
                code: string;
                message: string;
                /** @description Same value as the X-Request-Id response header. */
                request_id: string;
            };
        };
    };
    responses: {
        /** @description No, unknown or expired session (`unauthenticated`). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The yearbook does not exist or belongs to someone else (`not_found`); the two cannot be told apart. */
        YearbookNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `invalid_<field>` (title, school_name, class_name, graduation_year, motto, language, page_size, full_name, nickname, birthday, quote, hobbies, future_plans, limit, cursor), `unknown_field` or `invalid_body`. */
        YearbookInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request carries the session cookie but its Origin (or Referer) is missing or not allowed (`csrf_origin_mismatch`). */
        CsrfOriginMismatch: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Body over the 1 MiB cap (`payload_too_large`). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A body was sent with a Content-Type other than application/json (`unsupported_media_type`). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many attempts (`rate_limited`). */
        RateLimited: {
            headers: {
                /** @description Seconds until the oldest counted attempt leaves the window. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description All password-hashing slots stayed taken for 2 seconds (`busy`); retry shortly. */
        Busy: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No route matches this path. Error code `not_found`. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Wrong HTTP method for this path. Error code `method_not_allowed`. */
        MethodNotAllowed: {
            headers: {
                /** @description Methods this path accepts. */
                Allow?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description `smem_session=<32 random bytes, base64url>; Path=/; Max-Age=2592000; HttpOnly; SameSite=Lax` (plus `Secure` unless SMEM_ENV=dev). Only the token's SHA-256 is stored server-side. */
        SessionCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The database answered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ready";
                    };
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description The database did not answer in time. Error code `not_ready`; the body never carries driver error text (it is logged server-side). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Trimmed, lower-cased and normalised to Unicode NFC, so NFC and NFD spellings of one address are the same account (also at login). The local part (before the last `@`) is at most 64 bytes, and the address contains no control (Cc) or format (Cf) characters; otherwise `invalid_email`. */
                    email: string;
                    /**
                     * Format: password
                     * @description Normalised to Unicode NFKC before the length rules (counted in characters after normalisation) and before hashing, so NFC and NFD forms of the same password are equal.
                     */
                    password: string;
                    /** @description Normalised to Unicode NFC, then trimmed; stored and returned in that form. Control characters (Cc), format characters (Cf: zero-width space, bidi overrides and isolates, LRM/RLM, BOM) except U+200D (zero-width joiner, used in emoji sequences), and line or paragraph separators (Zl, Zp) are rejected with `invalid_display_name`. */
                    display_name: string;
                };
            };
        };
        responses: {
            /** @description Account created; the session cookie is set. */
            201: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description `invalid_email`, `weak_password`, `invalid_display_name` or `invalid_body`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            /** @description Email already registered (`email_taken`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Busy"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Trimmed, lower-cased and NFC-normalised as at registration, so either Unicode spelling signs in. */
                    email: string;
                    /**
                     * Format: password
                     * @description Normalised to Unicode NFKC before verification, exactly as at registration.
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Signed in; the session cookie is set. */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description Malformed body (`invalid_body`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Wrong email or password (`invalid_credentials`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Busy"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; the cookie is cleared. */
            204: {
                headers: {
                    /** @description smem_session with an empty value and a negative Max-Age. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfOriginMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description The address is verified (`email_verified` is now true). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_token` or `invalid_body`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    resendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The address was already verified; nothing was sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        already_verified: true;
                    };
                };
            };
            /** @description The email was sent. A mailer failure is `500 internal_error` (and is logged without the token). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                };
            };
        };
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description `invalid_email` or `invalid_body`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Password changed; all sessions are gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_token`, `weak_password` or `invalid_body`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            503: components["responses"]["Busy"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    /** @description Present only when the session expiry was extended. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description No, unknown or expired session (`unauthenticated`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listYearbooks: {
        parameters: {
            query?: {
                /** @description Out of range or not a number: `400 invalid_limit`. */
                limit?: number;
                /** @description Opaque token from a previous page. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of books (each with its profile). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        yearbooks: components["schemas"]["Yearbook"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["YearbookInvalid"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    createYearbook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YearbookCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearbookEnvelope"];
                };
            };
            400: components["responses"]["YearbookInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            /** @description The user already owns 20 yearbooks (`limit_reached`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    getYearbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The book. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearbookEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["YearbookNotFound"];
        };
    };
    deleteYearbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            404: components["responses"]["YearbookNotFound"];
        };
    };
    updateYearbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YearbookPatch"];
            };
        };
        responses: {
            /** @description The updated book. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearbookEnvelope"];
                };
            };
            400: components["responses"]["YearbookInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            404: components["responses"]["YearbookNotFound"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    replaceYearbookProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description The book with its updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearbookEnvelope"];
                };
            };
            400: components["responses"]["YearbookInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            404: components["responses"]["YearbookNotFound"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
}
