/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (pings the database, 1 s timeout) */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and sign in
         * @description Email is trimmed, lower-cased and normalised to NFC; a duplicate (case-insensitive, and NFC/NFD spellings are the same address) is `409 email_taken`. Password: 10-128 characters and not equal to the email. Display name: 1-100 characters after trimming, no control or format characters (see the field). Rate limit: 5 per hour per IP (counted once the input is valid). A cookie-less request needs no Origin; one that carries a session cookie must satisfy the CSRF origin check.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description A wrong password and an unknown email give the identical `401 invalid_credentials` (same body, same work). Every login issues a new session token; a session cookie sent with the request is revoked. Failures are limited to 10 per 15 minutes per IP+email and 100 per 15 minutes per IP.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out (idempotent)
         * @description Deletes the session and clears the cookie. Always 204, also when nobody is signed in.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an email address with the token from the verification email
         * @description Tokens are 32 random bytes (base64url), stored only as SHA-256, valid 24 hours and single use. An unknown, expired, used or wrong-purpose token (a reset token, for example) is `400 invalid_token`. Registration and `verify-email/resend` send the email; the link is `SMEM_PUBLIC_BASE_URL/verify-email?token=...`.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a new verification email to the signed-in user
         * @description At most 3 per hour per user (`429 rate_limited` with `Retry-After`). Earlier links stay valid until they expire. Takes no body.
         */
        post: operations["resendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a password reset email
         * @description Always `202 {}` for a well-formed address, whether or not an account exists; the email (valid link for 1 hour, in the user's `locale`) goes out in the background and only when the account exists, so neither the body nor the timing tells them apart. Limits: 5 per hour per IP and 3 per hour per address (counted for unknown addresses too). The address is trimmed, lower-cased and NFC-normalised like at login; one that is not an email at all is `400 invalid_email`.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with the token from the reset email
         * @description The token is valid 1 hour and single use; an unknown, expired, used or wrong-purpose token is `400 invalid_token`. The password follows the registration rules (NFKC, 10-128 characters, not the email); a rejected password is `400 weak_password` and does not use up the token. On success every session of the user is deleted (sign in again), and the user's other open reset links stop working.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Google sign-in (browser navigation, not a fetch call)
         * @description Only exists when the server has `SMEM_GOOGLE_CLIENT_ID` set; otherwise `404 not_found`. Redirects to Google's authorization endpoint (authorization-code flow with PKCE S256, `state` and `nonce`, scope `openid email profile`) and sets the 10-minute `smem_oidc` cookie (HttpOnly, SameSite=Lax, signed) that binds the flow to this browser. `return_to` must be a same-site relative path (one leading `/`, at most 200 characters, no `//`, `/\`, scheme or control characters); anything else is replaced by `/`. If Google cannot be reached the answer is `302 /login?error=oidc_failed`. 30 per 15 minutes per IP.
         */
        get: operations["googleStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google redirects the browser here after sign-in
         * @description Only exists when Google sign-in is enabled (else `404 not_found`). The redirect URI registered at Google is `<public base URL>/api/v1/auth/google/callback`. Success signs the user in (new `smem_session` cookie; a session cookie sent with the request is revoked) and redirects to the `return_to` given at start. Linking: a known Google account signs in; the same verified email on a local account links to it; the same email on a local account that never verified it first loses its password and sessions, is marked verified and linked (pre-hijacking defence); an unknown email creates a password-less account. Every failure is `302 /login?error=<code>` and creates nothing: `oidc_state` (cookie missing, altered or expired, or `state` differs), `oidc_denied` (the provider reported an error), `oidc_failed` (code exchange or ID-token check failed, or no usable email), `email_unverified` (Google did not mark the email verified). Provider details are only logged. 30 per 15 minutes per IP.
         */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user
         * @description Sliding expiry: once more than half of the 30-day lifetime has elapsed the expiry is extended and the cookie is sent again.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/yearbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's yearbooks
         * @description Only the caller's books, newest `updated_at` first (editing the book or its profile updates it). Pass `next_cursor` back as `cursor` for the next page; `next_cursor` is null on the last page. A malformed or tampered cursor is `400 invalid_cursor`.
         */
        get: operations["listYearbooks"];
        put?: never;
        /**
         * Create a yearbook (and its owner profile)
         * @description Creates the book and one owner profile whose `full_name` is the user's display name. A user owns at most 20 books (`409 limit_reached`). Unknown fields (for example `owner_id`) are rejected with `400 unknown_field`. Text fields are normalised to NFC and trimmed; control characters (Cc), format characters (Cf, except U+200D) and line/paragraph separators are rejected with `invalid_<field>`.
         */
        post: operations["createYearbook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/yearbooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Read one yearbook with its profile
         * @description A missing book and a book owned by someone else both answer `404 not_found`.
         */
        get: operations["getYearbook"];
        put?: never;
        post?: never;
        /**
         * Delete a yearbook
         * @description Hard-deletes the book, its profile and its stored photos. The photos are removed from object storage first; if that fails the request answers `502 storage_error` and nothing is deleted.
         */
        delete: operations["deleteYearbook"];
        options?: never;
        head?: never;
        /**
         * Partially update a yearbook
         * @description Only the fields present change. An empty string clears an optional text field; `graduation_year: null` clears the year. A JSON null on any other field counts as absent. Unknown fields are `400 unknown_field`.
         */
        patch: operations["updateYearbook"];
        trace?: never;
    };
    "/v1/yearbooks/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the owner's profile information
         * @description Replaces every field: an omitted optional field is cleared. Unknown fields (for example `is_owner`) are `400 unknown_field`. Birthday is personal data and is never logged.
         */
        put: operations["replaceYearbookProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/yearbooks/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a photo to a yearbook
         * @description `multipart/form-data` with the image in the part named `file`; other parts are ignored and the client file name is never used. The type is decided by sniffing the content (JPEG, PNG, WebP), never by file name or Content-Type. The image is decoded, rotated upright, stripped of all metadata (EXIF, GPS, ICC, comments), resized to at most 3000 px on the long edge (never enlarged) and stored; a 480 px JPEG thumbnail is stored too. Opaque images are stored as JPEG, images with transparency as PNG. Only the owner may upload (`404` otherwise). The body cap is `SMEM_MEDIA_MAX_BYTES` (default 10 MiB). Limits: 200 photos per yearbook, 500 MiB per user, 60 uploads per 10 minutes per user.
         */
        post: operations["uploadMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Media ULID. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Download a photo
         * @description Streams the stored image to the yearbook owner only (`404` for anyone else). `Content-Type` comes from the stored record. Honours `Range` and `If-None-Match`.
         */
        get: operations["getMediaContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Media ULID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a photo
         * @description Removes the row and both stored objects. Idempotent: an unknown id, an already deleted one and someone else's photo all answer `204` (and the last deletes nothing), so the answer never reveals whether a photo exists. A cover or profile photo that pointed at it is cleared.
         */
        delete: operations["deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/yearbooks/{id}/collections": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        /**
         * List a yearbook's collection links
         * @description Newest first, revoked ones included (`revoked_at` set). Never contains a token or a token hash. `note_count` counts notes in any status; it is 0 until notes can be submitted.
         */
        get: operations["listCollections"];
        put?: never;
        /**
         * Create a collection link for a yearbook
         * @description Creates a private link friends can use to leave notes. The body is a JSON object (send `{}` for no options). The response carries the link `token` once; only its SHA-256 is stored and it can never be shown again (revoke the link and create a new one instead). The token is a bearer secret of 192 random bits (32 base64url characters); the web link is `<app>/c/<token>`. `label` is optional, at most 60 characters, NFC and trimmed (`invalid_label` for control or format characters). `deadline_at` is optional, RFC 3339, in the future and at most one year ahead (`invalid_deadline`). Unknown fields are `400 unknown_field`. Needs a verified email (`403 email_not_verified`). A missing book and one owned by someone else both answer `404 not_found`. At most 5 active (not revoked) links per book (`409 limit_reached`).
         */
        post: operations["createCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ULID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a collection link
         * @description Sets `revoked_at`; the link stops working at once and never becomes active again. Repeating it is `204` as well. A missing link and someone else's both answer `404 not_found`.
         */
        delete: operations["revokeCollection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/public/collect/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The link token */
                token: string;
            };
            cookie?: never;
        };
        /**
         * Look up a collection link (public)
         * @description For the contributor form. No session is needed and none is read; no cookie is set and no CORS headers are sent. An unknown, malformed or revoked token all answer the same `404 not_found`. Once the deadline has passed the answer is `410 collection_closed`. Limited to 60 requests per client IP per 15 minutes (`429 rate_limited`, with `Retry-After`), valid or not. The token never appears in logs.
         */
        get: operations["lookupCollection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * @description Opaque ULID.
             * @example 01J9Z3K6V8Q4M7N2P5R8T0W1XY
             */
            id: string;
            email: string;
            email_verified: boolean;
            display_name: string;
            /** @enum {string} */
            locale: "en" | "vi";
            /** Format: date-time */
            created_at: string;
        };
        UserEnvelope: {
            user: components["schemas"]["User"];
        };
        Profile: {
            /** @description Opaque ULID. */
            id: string;
            is_owner: boolean;
            full_name: string;
            /** @description Empty when not set. */
            nickname: string;
            /** Format: date */
            birthday: string | null;
            quote: string;
            hobbies: string;
            future_plans: string;
            /** @description A photo of this yearbook */
            photo_media_id: string | null;
        };
        Yearbook: {
            /**
             * @description Opaque ULID.
             * @example 01J9Z3K6V8Q4M7N2P5R8T0W1XY
             */
            id: string;
            title: string;
            /** @description Empty when not set. */
            school_name: string;
            /** @description Empty when not set. */
            class_name: string;
            graduation_year: number | null;
            motto: string;
            /** @enum {string} */
            language: "en" | "vi";
            /** @enum {string} */
            page_size: "A5" | "A4" | "Letter";
            /** @description Null until a template is chosen. */
            template_id: string | null;
            /** @description A photo of this yearbook */
            cover_media_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            profile: components["schemas"]["Profile"];
        };
        YearbookEnvelope: {
            yearbook: components["schemas"]["Yearbook"];
        };
        YearbookCreate: {
            title: string;
            school_name?: string;
            class_name?: string;
            graduation_year?: number | null;
            motto?: string;
            /** @enum {string} */
            language: "en" | "vi";
            /**
             * @default A5
             * @enum {string}
             */
            page_size: "A5" | "A4" | "Letter";
        };
        YearbookPatch: {
            title?: string;
            school_name?: string;
            class_name?: string;
            graduation_year?: number | null;
            motto?: string;
            /** @enum {string} */
            language?: "en" | "vi";
            /** @enum {string} */
            page_size?: "A5" | "A4" | "Letter";
            /** @description A photo of this yearbook (else `400 invalid_media`); null clears it. */
            cover_media_id?: string | null;
        };
        ProfileInput: {
            full_name: string;
            nickname?: string;
            /**
             * Format: date
             * @description YYYY-MM-DD, a real date strictly before today (UTC) and not before 1900-01-01.
             */
            birthday?: string | null;
            quote?: string;
            hobbies?: string;
            future_plans?: string;
            /** @description A photo of this yearbook (else `400 invalid_media`). Like every field of this replacing PUT */
            photo_media_id?: string | null;
        };
        Media: {
            /** @description Opaque ULID. */
            id: string;
            /** @description Pixels */
            width: number;
            height: number;
            /** @description Size of the stored display version. */
            bytes: number;
        };
        MediaEnvelope: {
            media: components["schemas"]["Media"];
        };
        CollectionCreate: {
            label?: string;
            /**
             * Format: date-time
             * @description In the future
             */
            deadline_at?: string;
        };
        CollectionCreated: {
            /** @description Collection ULID. */
            id: string;
            label: string;
            /** Format: date-time */
            deadline_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** @description Shown only in this response. */
            token: string;
        };
        Collection: {
            id: string;
            label: string;
            /** Format: date-time */
            deadline_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            revoked_at: string | null;
            note_count: number;
        };
        CollectionPublic: {
            yearbook: {
                title: string;
            };
            owner: {
                display_name: string;
            };
            /** Format: date-time */
            deadline_at: string | null;
            /** @constant */
            open: true;
        };
        /** @description Shared error envelope. `code` is a stable snake_case contract (clients localise it); `message` is English text meant for logs. */
        Error: {
            error: {
                /**
                 * @example not_found
                 * @example method_not_allowed
                 * @example payload_too_large
                 * @example internal_error
                 * @example not_ready
                 * @example invalid_credentials
                 * @example unauthenticated
                 * @example rate_limited
                 * @example invalid_token
                 * @example limit_reached
                 * @example unknown_field
                 * @example unsupported_media_type
                 * @example invalid_image
                 * @example quota_exceeded
                 * @example storage_error
                 * @example invalid_media
                 */
                code: string;
                message: string;
                /** @description Same value as the X-Request-Id response header. */
                request_id: string;
            };
        };
    };
    responses: {
        /** @description No, unknown or expired session (`unauthenticated`). */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The yearbook does not exist or belongs to someone else (`not_found`); the two cannot be told apart. */
        YearbookNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `invalid_<field>` (title, school_name, class_name, graduation_year, motto, language, page_size, full_name, nickname, birthday, quote, hobbies, future_plans, limit, cursor, media: a `*_media_id` that is not a photo of this yearbook), `unknown_field` or `invalid_body`. */
        YearbookInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request carries the session cookie but its Origin (or Referer) is missing or not allowed (`csrf_origin_mismatch`). */
        CsrfOriginMismatch: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Body over the 1 MiB cap (`payload_too_large`). */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A body was sent with a Content-Type other than application/json (`unsupported_media_type`). */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many attempts (`rate_limited`). */
        RateLimited: {
            headers: {
                /** @description Seconds until the oldest counted attempt leaves the window. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The object store failed (`storage_error`); nothing was changed, retry later. */
        StorageError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description All password-hashing slots stayed taken for 2 seconds (`busy`); retry shortly. */
        Busy: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No route matches this path. Error code `not_found`. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Wrong HTTP method for this path. Error code `method_not_allowed`. */
        MethodNotAllowed: {
            headers: {
                /** @description Methods this path accepts. */
                Allow?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description `smem_session=<32 random bytes, base64url>; Path=/; Max-Age=2592000; HttpOnly; SameSite=Lax` (plus `Secure` unless SMEM_ENV=dev). Only the token's SHA-256 is stored server-side. */
        SessionCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
            404: components["responses"]["NotFound"];
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The database answered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ready";
                    };
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description The database did not answer in time. Error code `not_ready`; the body never carries driver error text (it is logged server-side). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Trimmed, lower-cased and normalised to Unicode NFC, so NFC and NFD spellings of one address are the same account (also at login). The local part (before the last `@`) is at most 64 bytes, and the address contains no control (Cc) or format (Cf) characters; otherwise `invalid_email`. */
                    email: string;
                    /**
                     * Format: password
                     * @description Normalised to Unicode NFKC before the length rules (counted in characters after normalisation) and before hashing, so NFC and NFD forms of the same password are equal.
                     */
                    password: string;
                    /** @description Normalised to Unicode NFC, then trimmed; stored and returned in that form. Control characters (Cc), format characters (Cf: zero-width space, bidi overrides and isolates, LRM/RLM, BOM) except U+200D (zero-width joiner, used in emoji sequences), and line or paragraph separators (Zl, Zp) are rejected with `invalid_display_name`. */
                    display_name: string;
                };
            };
        };
        responses: {
            /** @description Account created; the session cookie is set. */
            201: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description `invalid_email`, `weak_password`, `invalid_display_name` or `invalid_body`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            /** @description Email already registered (`email_taken`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Busy"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Trimmed, lower-cased and NFC-normalised as at registration, so either Unicode spelling signs in. */
                    email: string;
                    /**
                     * Format: password
                     * @description Normalised to Unicode NFKC before verification, exactly as at registration.
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Signed in; the session cookie is set. */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SessionCookie"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description Malformed body (`invalid_body`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Wrong email or password (`invalid_credentials`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["Busy"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; the cookie is cleared. */
            204: {
                headers: {
                    /** @description smem_session with an empty value and a negative Max-Age. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["CsrfOriginMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                };
            };
        };
        responses: {
            /** @description The address is verified (`email_verified` is now true). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_token` or `invalid_body`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    resendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The address was already verified; nothing was sent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        already_verified: true;
                    };
                };
            };
            /** @description The email was sent. A mailer failure is `500 internal_error` (and is logged without the token). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                };
            };
        };
        responses: {
            /** @description Accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description `invalid_email` or `invalid_body`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Password changed; all sessions are gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_token`, `weak_password` or `invalid_body`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["CsrfOriginMismatch"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            503: components["responses"]["Busy"];
        };
    };
    googleStart: {
        parameters: {
            query?: {
                return_to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description To Google (or to `/login?error=oidc_failed`). */
            302: {
                headers: {
                    Location?: string;
                    /** @description `smem_oidc`, valid 10 minutes. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    googleCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description To `return_to` (signed in) or to `/login?error=<code>`. */
            302: {
                headers: {
                    Location?: string;
                    /** @description `smem_session` on success; `smem_oidc` is always cleared. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    /** @description Present only when the session expiry was extended. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description No, unknown or expired session (`unauthenticated`). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listYearbooks: {
        parameters: {
            query?: {
                /** @description Out of range or not a number: `400 invalid_limit`. */
                limit?: number;
                /** @description Opaque token from a previous page. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of books (each with its profile). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        yearbooks: components["schemas"]["Yearbook"][];
                        next_cursor: string | null;
                    };
                };
            };
            400: components["responses"]["YearbookInvalid"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    createYearbook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YearbookCreate"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearbookEnvelope"];
                };
            };
            400: components["responses"]["YearbookInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            /** @description The user already owns 20 yearbooks (`limit_reached`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    getYearbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The book. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearbookEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["YearbookNotFound"];
        };
    };
    deleteYearbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            404: components["responses"]["YearbookNotFound"];
            502: components["responses"]["StorageError"];
        };
    };
    updateYearbook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YearbookPatch"];
            };
        };
        responses: {
            /** @description The updated book. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearbookEnvelope"];
                };
            };
            400: components["responses"]["YearbookInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            404: components["responses"]["YearbookNotFound"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    replaceYearbookProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileInput"];
            };
        };
        responses: {
            /** @description The book with its updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YearbookEnvelope"];
                };
            };
            400: components["responses"]["YearbookInvalid"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            404: components["responses"]["YearbookNotFound"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    uploadMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaEnvelope"];
                };
            };
            /** @description `invalid_image` (corrupt, over 12000 px on a side or over 50 megapixels) or `invalid_body` (not multipart or no `file` part). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            404: components["responses"]["YearbookNotFound"];
            /** @description A storage limit is reached (`quota_exceeded`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The file or the request body is over the cap (`payload_too_large`). */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The request is not `multipart/form-data`, or the file is not a JPEG, PNG or WebP image (`unsupported_media_type`). */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
            502: components["responses"]["StorageError"];
            /** @description Too many uploads in progress (`busy`); retry after the `Retry-After` seconds. */
            503: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMediaContent: {
        parameters: {
            query?: {
                size?: "display" | "thumb";
            };
            header?: never;
            path: {
                /** @description Media ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image. */
            200: {
                headers: {
                    "Cache-Control"?: "private, max-age=3600";
                    "X-Content-Type-Options"?: "nosniff";
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            /** @description The requested byte range. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not modified. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown `size` (`invalid_size`). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description Range not satisfiable. */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            502: components["responses"]["StorageError"];
        };
    };
    deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Media ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            502: components["responses"]["StorageError"];
        };
    };
    listCollections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The links. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        collections: components["schemas"]["Collection"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["YearbookNotFound"];
        };
    };
    createCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yearbook ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Created. The only response that ever contains the token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        collection: components["schemas"]["CollectionCreated"];
                    };
                };
            };
            /** @description `invalid_label`, `invalid_deadline`, `unknown_field` or `invalid_body`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            /** @description `email_not_verified` (the owner's email is not verified) or `csrf_origin_mismatch` (the request carries the session cookie but its Origin is not allowed). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["YearbookNotFound"];
            /** @description The book already has 5 active links (`limit_reached`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    revokeCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collection ULID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked (or already revoked). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["CsrfOriginMismatch"];
            404: components["responses"]["NotFound"];
        };
    };
    lookupCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The link token */
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The link is active. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionPublic"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description The deadline has passed (`collection_closed`). */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
}
