#!/usr/bin/env python3
"""Leader tool: prefix board titles with the epic code and regenerate .team/TASKS.md.

  python3 .team/epic_index.py            regenerate .team/TASKS.md (read-only on the board)
  python3 .team/epic_index.py --titles   also set every task title to "[E##] title" through board.py (locked, idempotent)

board.py recognises tasks only as T-nnn (heading, dependencies, branches, worktrees), so the id itself cannot carry the epic.
The epic code lives in the title and in the label E##_T-nnn used by TASKS.md.
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOARD = [sys.executable, "/Users/unisoft/.claude/plugins/cache/claude-agent-team/agent-team/0.3.0/scripts/board.py", "--as", "leader"]
README = os.path.join(ROOT, ".team", "README.md")

def parse():
    text = open(README, encoding="utf-8").read()
    start = text.index("<!-- tasks:start -->") if "<!-- tasks:start -->" in text else 0
    tasks = []
    for m in re.finditer(r"^### (T-\d+) [—–-]+ (.*?)\s*$(.*?)(?=^### [TQ]-\d+ |\Z)", text[start:], re.S | re.M):
        tid, title, body = m.group(1), m.group(2), m.group(3)
        meta = dict(re.findall(r"^- \*\*([A-Za-z -]+):\*\*[ \t]*(.*)$", body, re.M))
        epic = re.search(r"\*\*Epic:\*\*\s*(E\d+)", body) or re.search(r"\.team/epics/(E\d+)-", body)
        spec = re.search(r"`(\.team/epics/[^`]+\.md)`", body)
        tasks.append(dict(id=tid, title=title, epic=epic.group(1) if epic else "E??", spec=spec.group(1) if spec else "",
                          status=meta.get("Status", "?"), prio=meta.get("Priority", ""), risk=meta.get("Risk", ""),
                          deps=meta.get("Depends-on", "—")))
    return tasks

def epics():
    out = {}
    d = os.path.join(ROOT, ".team", "epics")
    for name in sorted(os.listdir(d)):
        m = re.match(r"(E\d+)-(.*)", name)
        if m:
            out[m.group(1)] = name
    return out

def write_index(tasks):
    ep = epics()
    lines = ["# Tasks by epic", "",
             "Generated by `python3 .team/epic_index.py` (do not edit). Label = `<epic>_<task id>`; the board and branches still use the plain `T-nnn`.", ""]
    for code in sorted({t["epic"] for t in tasks}):
        folder = ep.get(code, "")
        title = f"[{folder}](epics/{folder}/PRD.md)" if folder else code
        lines += [f"## {code} — {title}", "", "| Task | Status | Pri | Risk | Depends on | Title | Spec |", "|---|---|---|---|---|---|---|"]
        for t in sorted((t for t in tasks if t["epic"] == code), key=lambda t: int(t["id"][2:])):
            clean = re.sub(r"^\[E\d+\]\s*", "", t["title"])
            spec = f"[spec]({t['spec'][len('.team/'):]})" if t["spec"] else ""
            lines.append(f"| `{code}_{t['id']}` | {t['status']} | {t['prio']} | {t['risk']} | {t['deps']} | {clean} | {spec} |")
        lines.append("")
    open(os.path.join(ROOT, ".team", "TASKS.md"), "w", encoding="utf-8").write("\n".join(lines))

def main():
    tasks = parse()
    if "--titles" in sys.argv:
        for t in tasks:
            if not re.match(r"\[E\d+\]", t["title"]):
                new = f"[{t['epic']}] {t['title']}"
                r = subprocess.run(BOARD + ["set", t["id"], "title=" + new], capture_output=True, text=True)
                print(r.stdout.strip() or r.stderr.strip())
        tasks = parse()
    write_index(tasks)
    print(f"{len(tasks)} tasks, {len({t['epic'] for t in tasks})} epics -> .team/TASKS.md")
    bad = [t["id"] for t in tasks if t["epic"] == "E??"]
    if bad:
        print("no epic found for:", ", ".join(bad))

main()
